apiVersion: apps/v1
kind: Deployment
metadata:
  name: agroapi-api
  namespace: agro-iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agroapi-api
  template:
    metadata:
      labels:
        app: agroapi-api
    spec:
      containers:
        - name: agroapi-api
          image: services-agroapi-api:latest
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_URLS
              value: "http://+:8081"
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: db-conn-secret
                  key: ConnectionStrings__DefaultConnection
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: agroapi-api
  namespace: agro-iot
spec:
  selector:
    app: agroapi-api
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
