apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-services
  namespace: agro-iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-services
  template:
    metadata:
      labels:
        app: api-services
    spec:
      containers:
        - name: api-services
          image: services-api-services:latest
          env:
            - name: PORT
              value: "3001"
            - name: MONGO_URI
              value: "mongodb://mongo:27017/agro-iot-platform"
          ports:
            - containerPort: 3001
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: api-services
  namespace: agro-iot
spec:
  selector:
    app: api-services
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP
