// <auto-generated />
using System;
using AgroAPI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgroAPI.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251001142533_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgroAPI.Domain.Entities.Cultivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cultivos");
                });

            modelBuilder.Entity("AgroAPI.Domain.Entities.Parcela", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CantidadCultivos")
                        .HasColumnType("int");

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Parcelas");
                });

            modelBuilder.Entity("AgroAPI.Domain.Entities.ParcelaCultivo", b =>
                {
                    b.Property<Guid>("ParcelaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CultivoId")
                        .HasColumnType("int");

                    b.HasKey("ParcelaId", "CultivoId");

                    b.HasIndex("CultivoId");

                    b.ToTable("ParcelaCultivos");
                });

            modelBuilder.Entity("AgroAPI.Domain.Entities.ParcelaUsuario", b =>
                {
                    b.Property<Guid>("ParcelaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ParcelaId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ParcelaUsuarios");
                });

            modelBuilder.Entity("AgroAPI.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AgroAPI.Domain.Entities.ParcelaCultivo", b =>
                {
                    b.HasOne("AgroAPI.Domain.Entities.Cultivo", "Cultivo")
                        .WithMany("ParcelaCultivos")
                        .HasForeignKey("CultivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgroAPI.Domain.Entities.Parcela", "Parcela")
                        .WithMany("ParcelaCultivos")
                        .HasForeignKey("ParcelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cultivo");

                    b.Navigation("Parcela");
                });

            modelBuilder.Entity("AgroAPI.Domain.Entities.ParcelaUsuario", b =>
                {
                    b.HasOne("AgroAPI.Domain.Entities.Parcela", "Parcela")
                        .WithMany("ParcelaUsuarios")
                        .HasForeignKey("ParcelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgroAPI.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ParcelaUsuarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parcela");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AgroAPI.Domain.Entities.Cultivo", b =>
                {
                    b.Navigation("ParcelaCultivos");
                });

            modelBuilder.Entity("AgroAPI.Domain.Entities.Parcela", b =>
                {
                    b.Navigation("ParcelaCultivos");

                    b.Navigation("ParcelaUsuarios");
                });

            modelBuilder.Entity("AgroAPI.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("ParcelaUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
